# Generated by Django 5.0.3 on 2024-06-03 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labridge_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='website',
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(default='default address', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='description',
            field=models.TextField(default='default description'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labridge_app.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labridge_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labridge_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labridge_app.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Supply',
        ),
    ]
